apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::514104879001:role/EKSWorkerNodeRole
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::514104879001:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-27T14:42:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3830"
  uid: bf77520e-3947-47db-966e-f8e76799df79
